Update OSRM network build

diff --git a/.github/workflows/create-osrm-networks.yaml b/.github/workflows/create-osrm-networks.yaml
--- a/.github/workflows/create-osrm-networks.yaml
+++ b/.github/workflows/create-osrm-networks.yaml
@@ -1,7 +1,7 @@
 ---
 
-name: create-valhalla-tiles
-run-name: create-valhalla-tiles-${{ inputs.year }}
+name: create-osrm-networks
+run-name: create-osrm-network-${{ inputs.year }}-${{ inputs.mode }}
 
 on:
   workflow_dispatch:
@@ -17,6 +17,13 @@ on:
           - '2022'
           - '2023'
           - '2024'
+
+      override_modes:
+        required: false
+        description: |
+          Comma-separated list of OSRM modes to run e.g. car,foot.
+          Will run all if null
+        type: string
 
       override_states:
         required: false
@@ -36,16 +43,12 @@ jobs:
     runs-on: ubuntu-24.04
 
     outputs:
+      modes: ${{ steps.create-job-chunks.outputs.modes }}
       states: ${{ steps.create-job-chunks.outputs.states }}
 
     steps:
       - name: Checkout
         uses: actions/checkout@v4
-
-      - name: Build Dockerized dependencies
-        uses: ./.github/actions/build-docker
-        with:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Create job chunks
         id: create-job-chunks
@@ -72,6 +75,27 @@ jobs:
             echo "Creating jobs for states: ${states_parsed[@]}"
           fi
 
+          modes=$(yq e -o=json '.times.mode' ./data/params.yaml | jq -c -s .[])
+          echo "modes=$(echo $modes)" >> $GITHUB_OUTPUT
+
+          # If override modes are set, use those instead
+          modes_parsed=($(echo "$modes" | jq -r '.[]'))
+          if [ -n "${{ inputs.override_modes }}" ]; then
+            override_modes_parsed=($(echo "${{ inputs.override_modes }}" | tr -d ' ' | tr ',' ' '))
+            for state in "${override_modes_parsed[@]}"; do
+              if [[ ! " ${modes_parsed[@]} " =~ " ${mode} " ]]; then
+                echo "Error: Override mode ${mode} is not in the modes for this workflow"
+                echo "Modes include: ${modes_parsed[@]}"
+                exit 1
+              fi
+            done
+            modes_json=$(printf '%s\n' "${override_modes_parsed[@]}" | jq -c -R . | jq -c -s .)
+            echo "Creating jobs for modes: ${override_modes_parsed[@]}"
+            echo "modes=$modes_json" > $GITHUB_OUTPUT
+          else
+            echo "Creating jobs for modes: ${modes_parsed[@]}"
+          fi
+
   run-job:
     runs-on: ubuntu-24.04
     needs: setup-jobs
@@ -79,6 +103,7 @@ jobs:
       # Don't fail all chunks if one fails
       fail-fast: false
       matrix:
+        mode: ${{ fromJSON(needs.setup-jobs.outputs.modes) }}
         state: ${{ fromJSON(needs.setup-jobs.outputs.states) }}
 
     steps:
@@ -94,17 +119,6 @@ jobs:
       - name: Install DVC
         uses: ./.github/actions/setup-dvc
 
-      - name: Fetch Docker image
-        uses: actions/download-artifact@v4
-        with:
-          name: opentimes-docker-${{ hashFiles('./data/Dockerfile', './pyproject.toml') }}
-          path: /tmp
-
-      - name: Load Docker image
-        run: |
-          docker load --input /tmp/opentimes.tar
-          docker image ls -a
-
       - name: Pull DVC objects
         shell: bash
         working-directory: 'data'
@@ -115,18 +129,15 @@ jobs:
       - name: Run job chunk
         shell: bash
         working-directory: 'data'
-        env:
-          # Disable elevation for Alaska (which requires 22GB of tiles)
-          BUILD_ELEVATION: ${{ matrix.state == '02' && 'False' || 'True' }}
         run: |
-          uv dvc repro -s create_valhalla_tiles@${{ inputs.year }}-${{ matrix.state }}
+          uv dvc repro -s create_osrmnetwork_by_state@${{ inputs.year }}-${{ matrix.state }}-${{ matrix.mode }}
 
-      - name: Write tile files to S3
+      - name: Write network files to S3
         shell: bash
         working-directory: 'data'
         run: |
           aws s3 cp --quiet --endpoint-url \
             https://${{ vars.CLOUDFLARE_ACCOUNT_ID }}.r2.cloudflarestorage.com \
-             ./intermediate/valhalla_tiles/year=${{ inputs.year }}/geography=state/state=${{ matrix.state }}/valhalla_tiles.tar.zst \
-             s3://opentimes-resources/valhalla_tiles/year=${{ inputs.year }}/geography=state/state=${{ matrix.state }}/valhalla_tiles.tar.zst \
+             ./intermediate/osrmnetwork/year=${{ inputs.year }}/geography=state/state=${{ matrix.state }}/mode=${{ matrix.mode }}/osrmnetwork.tar.zst \
+             s3://opentimes-resources/osrmnetwork/year=${{ inputs.year }}/geography=state/state=${{ matrix.state }}/mode=${{ matrix.mode }}/osrmnetwork.tar.zst \
             --profile cloudflare
